### ISSUE TITLE
Error when trying to send transactions

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrandroid#157]
Whenever I try to send a transaction, I get an error screen. I even wiped my data, re-imported the seed, but still got the same error message. It happens before I can enter my password.

Version MD5: 46782290168911AD8CF97D2867499956
Device: Moto G5
OS: Android 7.0
Error was reproduced on the same device

![image](https://user-images.githubusercontent.com/16287891/46669933-1c684900-cbd1-11e8-873b-e88c148fb274.png)

**Comment by C-ollins** [comment]
Stack Trace
```
java.util.IllegalFormatConversionException: x != java.lang.String 
at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4135) 
at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2832) 
at java.util.Formatter$FormatSpecifier.print(Formatter.java:2786) 
at java.util.Formatter.format(Formatter.java:2491) 
at java.util.Formatter.format(Formatter.java:2426) 
at java.lang.String.format(String.java:2670) 
at com.dcrandroid.fragments.SendFragment.showInputPassPhraseDialog(SendFragment.java:725) 
at com.dcrandroid.fragments.SendFragment$2.onClick(SendFragment.java:168) 
at android.view.View.performClick(View.java:5612) 
at android.view.View$PerformClick.run(View.java:22288) 
at android.os.Handler.handleCallback(Handler.java:751) 
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6123)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```
